-- Run this SQL in your Supabase SQL editor.

create table if not exists public.pickup_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  type text not null,
  message text default '',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.pickup_requests enable row level security;

-- The website uses the server-side service-role key.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY in client-side code.